refactor: removed create config step in serve
razorpay/citadel pull request #263
Opened 2021-11-30 08:06 UTC by neeraj719714

2021-12-02 08:14 UTC, anshulsahni approved these changes
Approving this with minor comments, please consider them before merting

2021-12-02 08:14 UTC, anshulsahni commented on server.js
> +  // createRedirects(config); not needed in case of serve
@neeraj719714 no need of commenting it, remove this line if it's not required

2021-12-02 08:14 UTC, anshulsahni commented on server.js
> +  // createRedirects(config); not needed in case of serve
@sidag95 Sure that server is only used in case of development in local and not for building things in production or staging?

2021-12-02 10:22 UTC, sidag95 commented on server.js
> +  // createRedirects(config); not needed in case of serve
@neeraj719714 @anshulsahni We need to have a redirect on local as well, why are we removing this from here? If this is slowing things down for fast refresh, let's do this once on startup instead of on every run

2021-12-02 10:22 UTC, sidag95 commented on server.js
> +  // createRedirects(config); not needed in case of serve
Yes, serve is only for local dev

2021-12-02 10:23 UTC, sidag95 requested changes
Let's not remove this altogher

2021-12-06 06:27 UTC, sidag95 commented on index.js
> +  if (shouldCreateRedirects) {
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** Shall we move this inside isServer since, build always creates redirects https://github.com/razorpay/citadel/pull/263/files#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fR167

2021-12-06 06:29 UTC, sidag95 commented on index.js
> +  if (shouldCreateRedirects) {
How will this work when nodemon re-runs the entire script? Won't this create redirects functions be called again and again🤔

2021-12-06 07:19 UTC, sidag95 approved these changes
LGTM

2021-12-07 05:38 UTC, anshulsahni commented
@neeraj719714 we're doing a major fix, though it might look minor, please update the description

2021-12-07 05:39 UTC, anshulsahni reviewed
Added one comment @neeraj719714 please check

2021-12-07 05:39 UTC, anshulsahni commented on index.js
> +const shouldCreateRedirects = argv._.indexOf('create-redirect') !== -1;
what does this mean, will we pass the `create-redirect` flag from command? if yes, then this is gonna affect Tech Writer's flow?

2021-12-09 05:59 UTC, merged